repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      # Run the linter with isort rules
      - id: ruff
        name: ruff check (isort)
        args: [--select, I, --fix]
        files: ^tiptop/
      # Run the formatter
      - id: ruff-format
        name: ruff format
        files: ^tiptop/
